#+title:About
[[file:https://jacobwalte.rs/index.org][Home]] [[file:https://jacobwalte.rs/about.org][About]] [[file:https://jacobwalte.rs/contact.org][Contact]] [[file:https://jacobwalte.rs/archive.org][Archive]]

** About Me
I am a first year PhD student at the University of Edinburgh, researching programming language theory (PL) under the supervision of [[https://denotational.co.uk/][Dr. Ohad Kammar]].
I also did my undergraduate degree in Computer Science and Mathematics here.

In the past, I've worked with Ohad on implementing an ML-style module system for [[https://idris-lang.org/][Idris 2]], a dependently typed language.
We also worked together on a [[https://github.com/idris-bayes/monad-bayes][probabilistic programming DSL/library]] in Idris, with an accompanying [[https://github.com/idris-bayes/melocule][probabilistic music composition tool]].

In 2023, I co-founded [[https://typesig.pl][TypeSig]], a student special interest group at UoE, which aims to get undergraduates interested in theoretical computer science.
TypeSig runs weekly Lean workshops and regular academic talks (from the likes of [[https://homepages.inf.ed.ac.uk/wadler/][Phil Wadler]], [[https://math.ucr.edu/home/baez/][John Baez]] and [[https://www.ma.ic.ac.uk/~buzzard/][Kevin Buzzard]]). 
We also ran our very own [[https://typesig.pl/resources/domain-theory][lecture series]] and [[https://typesig.pl/tuple/][conference]]!
I also developed and ran a [[https://typesig.pl/resources/lang-workshop][tutorial series]] teaching first year students how to implement a functional programming language called MLTS.

My main academic interests lie in
programming language theory (PL),
type theory,
quantum computing,
and category theory.

Outside of research, I enjoy synthesizers (both playing and making them), reading, and listening to and making music.
In order to truly fit the PL stereotype, I've recently taken up climbing.

Here's a map of countries I've been to:
[[./static/images/countries.svg]]
(you can find the script that made this image [[https://github.com/jacobjwalters/countries][here]])

** About this Site
You can read in detail about how this site is made in [[./posts/website.org][this post]], but the gist is: this site is generated from a set of Org files using [[https://jaspervdj.be/hakyll/][Hakyll]] (and [[https://pandoc.org/][Pandoc]]), and served to you via Github Pages.

I've used literate programming to document the [[./static/style.org][CSS]] and [[./static/js.org][JS]] for this site. The actual =.css= and =.js= files are generated directly from the previously linked pages.

You can also browse this site entirely from within Emacs using Org mode! Find out how [[./posts/serving-websites-over-org.org][here]].

Any code snippets on this site are released into the public domain, except where otherwise noted.
All art assets are my copyright, except where otherwise noted.

