---
title: About
description: Find out about me and my interests, as well as how this site is run!
---
* About me
I am a fourth and final year student of Computer Science and Mathematics at the University of Edinburgh.

I'm working with [[https://denotational.co.uk/][Ohad Kammar]] on implementing an ML-style module system for [[https://idris-lang.org/][Idris 2]], a dependently typed language. Previously, we worked together on a [[https://github.com/idris-bayes/monad-bayes][probabilistic programming DSL/library]] in Idris, with an accompanying [[https://github.com/idris-bayes/melocule][probabilistic music composition tool]].

I'm also a co-founder and the vice president of [[https://typesig.comp-soc.com][TypeSig]], a brand new student special interest group in Edinburgh, which helps get undergraduates interested in theoretical computer science. We run weekly Lean workshops, regular academic talks (from the likes of [[https://homepages.inf.ed.ac.uk/wadler/][Phil Wadler]], [[https://math.ucr.edu/home/baez/][John Baez]] and [[https://www.ma.ic.ac.uk/~buzzard/][Kevin Buzzard]]), and we're organising a conference to be held in 2024!

My interests in CS areas are in programming language theory, type theory, probabilistic programming compiler design, operating systems and low level computing, and hardware synthesis. I'm also interested in cyber security, though mainly as a hobby.

My mathematical intrigues lie mostly in category theory, abstract algebra, cryptography, and of course logic.

Outside of the nerd life, I enjoy synthesizers (playing and making them), reading, and eclectic (read: bad) music.

Here's a map of where I've been:
[[file:images/countries.svg][A map showing countries that I've lived in or visited. The UK is marked as lived in, and most of western Europe is visited.]]
(you can find the script that made this image [[https://github.com/jacobjwalters/countries][here]])

* About this site
You can read in detail about how this site is made in [[file:posts/2023-05-12-website.org][this post]], but the gist is: this site is generated from a set of Org files using [[https://jaspervdj.be/hakyll/][Hakyll]] (and [[https://pandoc.org/][Pandoc]]), and served to you using [[https://caddyserver.com/][Caddy]]. It's hosted on a VPS from [[https://contabo.com][Contabo]], which I've infected with [[https://nixos.org][NixOS]]. I thoroughly recommend all of these.

The CSS I'm currently using is a modified [[https://edwardtufte.github.io/tufte-css/][tufte-css]]. This allows for the nice side and margin notes you can see throughout my site. To aid writing with this, I use [[https://hackage.haskell.org/package/pandoc-sidenote][pandoc-sidenote]] in my pandoc compiler to convert standard markdown footnote syntax into sidenotes and margin notes.

You can alo browse this site entirely from within Emacs using Org mode! Find out how [[file:posts/2023-05-17-serving-websites-over-org.org][here]].

Any code snippets on this site are released into the public domain, except where otherwise noted. All art assets are my copyright, except where otherwise noted.
