# https://github.com/zfhrp6/hakyll-github-actions/blob/master/.github/workflows/hakyll.yaml
name: hakyll CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache stack folder
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
        
    - name: Install Dependencies
      run: sudo apt install -y pkg-config zlib1g-dev stack
      
    - name: Build Site
      run: |
        cd ${{ github.workspace }}
        make build
      
    - name: Deploy over SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        # source to copy from
        source: ${{ github.workspace }}/_site
        # destination to download on server
        target: ${{ secrets.DEPLOY_DIR }}
        rm: true
