# https://github.com/zfhrp6/hakyll-github-actions/blob/master/.github/workflows/hakyll.yaml
name: hakyll CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the stack container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/hakyll -v ${{ github.workspace }}/_site:/srv/hakyll/_site \
        fpco/stack-build-small:latest /bin/bash -c \
        "chmod 777 /srv/hakyll && \
         sudo apt-get install -y pkg-config zlib1g-dev \
         cd /srv/hakyll && \
         stack install --allow-different-user && \
         stack build --allow-different-user --fast && \
         stack exec site build"
    - name: list artifacts
      run: find ${{ github.workspace }}/_site
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: ${{ secrets.DEPLOYSCRIPT }}

